name: Auto Tag on push

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Get Version from Code
      id: get_version
      run: |
        pip install toml
        python update_version.py
        VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml', 'r'))['project']['version'])")
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Log Version
      run: echo "Version is ${{ env.VERSION }}"

    # - name: Create Tag
    #   run: |
    #     git tag -a ${{ env.VERSION }} -m "Version ${{ env.VERSION }}"
    #     git push origin ${{ env.VERSION }}