# This builds the docker image and pushes it to DockerHub

name: Docker push

on:
  push:
    branches:
      - main
      - dev

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_dockerhub:
    name: Docker push
    runs-on: ubuntu-latest
    # Only run for the main FrancisCrick repo
    if: ${{ github.repository == 'crick-pipelines-stp/crick-genome-tools' }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: thecrick/pipetech_genome_tools
            dockerfile: Dockerfile
          - image: thecrick/pipetech_iterative_alignment
            dockerfile: containers/iterative_alignment/Dockerfile
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set Docker Tag
        id: set-docker-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=tag::latest"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=tag::dev"
          fi

      - name: Get Version
        id: get_version
        run: |
          pip install toml
          python update_version.py
          VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml', 'r'))['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache  -f ${{ matrix.dockerfile }} -t ${{ matrix.image }}:${{ steps.set-docker-tag.outputs.tag }} -f ${{ matrix.dockerfile }} .
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker build --no-cache -f ${{ matrix.dockerfile }} -t ${{ matrix.image }}:${{ env.VERSION }} .
          fi

      - name: Push Docker images
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push ${{ matrix.image }}:${{ steps.set-docker-tag.outputs.tag }}
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            docker push ${{ matrix.image }}:${{ env.VERSION }}
          fi
