# This builds the docker image and pushes it to DockerHub

name: Docker push

on:
  push:
    branches:
      - main
      - dev

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  push_dockerhub:
    name: Docker push Main Library
    runs-on: ubuntu-latest
    # Only run for the main FrancisCrick repo
    if: ${{ github.repository == 'crick-pipelines-stp/crick-genome-tools' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set Docker general tag
        id: set-docker-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=tag::latest"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=tag::dev"
          fi

      - name: Get Version from Code
        id: get_version
        run: |
          pip install toml
          python update_version.py
          VERSION=$(python -c "import toml; print(toml.load(open('pyproject.toml', 'r'))['project']['version'])")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build --no-cache . -t thecrick/pipetech_genome_tools:${{ steps.set-docker-tag.outputs.tag }}
          docker build --no-cache . -t thecrick/pipetech_genome_tools:${{ env.VERSION }}

      - name: Push Docker images to DockerHub (release)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push thecrick/pipetech_genome_tools:${{ steps.set-docker-tag.outputs.tag }}
          docker push thecrick/pipetech_genome_tools:${{ env.VERSION }}

  push_iter_align:
    name: Docker push Iter Align
    runs-on: ubuntu-latest
    # Only run for the main FrancisCrick repo
    if: ${{ github.repository == 'crick-pipelines-stp/crick-genome-tools' }}
    env:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASS: ${{ secrets.DOCKERHUB_PASS }}
    strategy:
      fail-fast: false
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history and tags

      - name: Set Docker tag
        id: set-docker-tag
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            echo "::set-output name=tag::latest"
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            echo "::set-output name=tag::dev"
          fi

      - name: Build Docker image
        run: docker build --no-cache --target prod -f containers/iterative_alignment/Dockerfile -t thecrick/pipetech_iterative_alignment:${{ steps.set-docker-tag.outputs.tag }} .

      - name: Push Docker images to DockerHub (release)
        run: |
          echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker push thecrick/pipetech_iterative_alignment:${{ steps.set-docker-tag.outputs.tag }}
